// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.25.0
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: rpc_test.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetChordNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetChordNodeRequest) Reset() {
	*x = GetChordNodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChordNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChordNodeRequest) ProtoMessage() {}

func (x *GetChordNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChordNodeRequest.ProtoReflect.Descriptor instead.
func (*GetChordNodeRequest) Descriptor() ([]byte, []int) {
	return file_rpc_test_proto_rawDescGZIP(), []int{0}
}

func (x *GetChordNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetChordNodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip   string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port int32  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *GetChordNodeResponse) Reset() {
	*x = GetChordNodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChordNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChordNodeResponse) ProtoMessage() {}

func (x *GetChordNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChordNodeResponse.ProtoReflect.Descriptor instead.
func (*GetChordNodeResponse) Descriptor() ([]byte, []int) {
	return file_rpc_test_proto_rawDescGZIP(), []int{1}
}

func (x *GetChordNodeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetChordNodeResponse) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *GetChordNodeResponse) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type GetRequestFromClient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input string `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
}

func (x *GetRequestFromClient) Reset() {
	*x = GetRequestFromClient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_test_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequestFromClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestFromClient) ProtoMessage() {}

func (x *GetRequestFromClient) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_test_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestFromClient.ProtoReflect.Descriptor instead.
func (*GetRequestFromClient) Descriptor() ([]byte, []int) {
	return file_rpc_test_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequestFromClient) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type GetResponseToClient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InputFromClient string `protobuf:"bytes,1,opt,name=inputFromClient,proto3" json:"inputFromClient,omitempty"`
	Id              string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Ip              string `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Port            int32  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *GetResponseToClient) Reset() {
	*x = GetResponseToClient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_test_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponseToClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponseToClient) ProtoMessage() {}

func (x *GetResponseToClient) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_test_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponseToClient.ProtoReflect.Descriptor instead.
func (*GetResponseToClient) Descriptor() ([]byte, []int) {
	return file_rpc_test_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponseToClient) GetInputFromClient() string {
	if x != nil {
		return x.InputFromClient
	}
	return ""
}

func (x *GetResponseToClient) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetResponseToClient) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *GetResponseToClient) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type CreateRingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *CreateRingRequest) Reset() {
	*x = CreateRingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_test_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRingRequest) ProtoMessage() {}

func (x *CreateRingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_test_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRingRequest.ProtoReflect.Descriptor instead.
func (*CreateRingRequest) Descriptor() ([]byte, []int) {
	return file_rpc_test_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRingRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CreateRingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HashedID           int64  `protobuf:"varint,1,opt,name=hashedID,proto3" json:"hashedID,omitempty"`
	Address            string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	SuccessorAddress   string `protobuf:"bytes,3,opt,name=successorAddress,proto3" json:"successorAddress,omitempty"`
	PredecessorAddress string `protobuf:"bytes,4,opt,name=predecessorAddress,proto3" json:"predecessorAddress,omitempty"`
}

func (x *CreateRingResponse) Reset() {
	*x = CreateRingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_test_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRingResponse) ProtoMessage() {}

func (x *CreateRingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_test_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRingResponse.ProtoReflect.Descriptor instead.
func (*CreateRingResponse) Descriptor() ([]byte, []int) {
	return file_rpc_test_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRingResponse) GetHashedID() int64 {
	if x != nil {
		return x.HashedID
	}
	return 0
}

func (x *CreateRingResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateRingResponse) GetSuccessorAddress() string {
	if x != nil {
		return x.SuccessorAddress
	}
	return ""
}

func (x *CreateRingResponse) GetPredecessorAddress() string {
	if x != nil {
		return x.PredecessorAddress
	}
	return ""
}

type JoinRingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JoinAddress string `protobuf:"bytes,2,opt,name=joinAddress,proto3" json:"joinAddress,omitempty"`
}

func (x *JoinRingRequest) Reset() {
	*x = JoinRingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_test_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRingRequest) ProtoMessage() {}

func (x *JoinRingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_test_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRingRequest.ProtoReflect.Descriptor instead.
func (*JoinRingRequest) Descriptor() ([]byte, []int) {
	return file_rpc_test_proto_rawDescGZIP(), []int{6}
}

func (x *JoinRingRequest) GetJoinAddress() string {
	if x != nil {
		return x.JoinAddress
	}
	return ""
}

type JoinRingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HashedID           int64  `protobuf:"varint,1,opt,name=hashedID,proto3" json:"hashedID,omitempty"`
	Address            string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	SuccessorAddress   string `protobuf:"bytes,3,opt,name=successorAddress,proto3" json:"successorAddress,omitempty"`
	PredecessorAddress string `protobuf:"bytes,4,opt,name=predecessorAddress,proto3" json:"predecessorAddress,omitempty"`
}

func (x *JoinRingResponse) Reset() {
	*x = JoinRingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_test_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRingResponse) ProtoMessage() {}

func (x *JoinRingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_test_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRingResponse.ProtoReflect.Descriptor instead.
func (*JoinRingResponse) Descriptor() ([]byte, []int) {
	return file_rpc_test_proto_rawDescGZIP(), []int{7}
}

func (x *JoinRingResponse) GetHashedID() int64 {
	if x != nil {
		return x.HashedID
	}
	return 0
}

func (x *JoinRingResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *JoinRingResponse) GetSuccessorAddress() string {
	if x != nil {
		return x.SuccessorAddress
	}
	return ""
}

func (x *JoinRingResponse) GetPredecessorAddress() string {
	if x != nil {
		return x.PredecessorAddress
	}
	return ""
}

type StabilizeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IpAddress string `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
}

func (x *StabilizeRequest) Reset() {
	*x = StabilizeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_test_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StabilizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StabilizeRequest) ProtoMessage() {}

func (x *StabilizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_test_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StabilizeRequest.ProtoReflect.Descriptor instead.
func (*StabilizeRequest) Descriptor() ([]byte, []int) {
	return file_rpc_test_proto_rawDescGZIP(), []int{8}
}

func (x *StabilizeRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type StabilizeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SuccessorAddress string `protobuf:"bytes,1,opt,name=successor_address,json=successorAddress,proto3" json:"successor_address,omitempty"`
}

func (x *StabilizeResponse) Reset() {
	*x = StabilizeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_test_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StabilizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StabilizeResponse) ProtoMessage() {}

func (x *StabilizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_test_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StabilizeResponse.ProtoReflect.Descriptor instead.
func (*StabilizeResponse) Descriptor() ([]byte, []int) {
	return file_rpc_test_proto_rawDescGZIP(), []int{9}
}

func (x *StabilizeResponse) GetSuccessorAddress() string {
	if x != nil {
		return x.SuccessorAddress
	}
	return ""
}

type GetPredecessorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IpAddress string `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
}

func (x *GetPredecessorRequest) Reset() {
	*x = GetPredecessorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_test_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPredecessorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPredecessorRequest) ProtoMessage() {}

func (x *GetPredecessorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_test_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPredecessorRequest.ProtoReflect.Descriptor instead.
func (*GetPredecessorRequest) Descriptor() ([]byte, []int) {
	return file_rpc_test_proto_rawDescGZIP(), []int{10}
}

func (x *GetPredecessorRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type GetPredecessorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PredecessorAddress string `protobuf:"bytes,1,opt,name=predecessor_address,json=predecessorAddress,proto3" json:"predecessor_address,omitempty"`
}

func (x *GetPredecessorResponse) Reset() {
	*x = GetPredecessorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_test_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPredecessorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPredecessorResponse) ProtoMessage() {}

func (x *GetPredecessorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_test_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPredecessorResponse.ProtoReflect.Descriptor instead.
func (*GetPredecessorResponse) Descriptor() ([]byte, []int) {
	return file_rpc_test_proto_rawDescGZIP(), []int{11}
}

func (x *GetPredecessorResponse) GetPredecessorAddress() string {
	if x != nil {
		return x.PredecessorAddress
	}
	return ""
}

type NotifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IpAddress string `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
}

func (x *NotifyRequest) Reset() {
	*x = NotifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_test_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRequest) ProtoMessage() {}

func (x *NotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_test_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRequest.ProtoReflect.Descriptor instead.
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return file_rpc_test_proto_rawDescGZIP(), []int{12}
}

func (x *NotifyRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type NotifyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PredecessorAddress string `protobuf:"bytes,1,opt,name=predecessor_address,json=predecessorAddress,proto3" json:"predecessor_address,omitempty"`
}

func (x *NotifyResponse) Reset() {
	*x = NotifyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_test_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyResponse) ProtoMessage() {}

func (x *NotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_test_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyResponse.ProtoReflect.Descriptor instead.
func (*NotifyResponse) Descriptor() ([]byte, []int) {
	return file_rpc_test_proto_rawDescGZIP(), []int{13}
}

func (x *NotifyResponse) GetPredecessorAddress() string {
	if x != nil {
		return x.PredecessorAddress
	}
	return ""
}

type CheckPredecessorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CheckPredecessorRequest) Reset() {
	*x = CheckPredecessorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_test_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckPredecessorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPredecessorRequest) ProtoMessage() {}

func (x *CheckPredecessorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_test_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPredecessorRequest.ProtoReflect.Descriptor instead.
func (*CheckPredecessorRequest) Descriptor() ([]byte, []int) {
	return file_rpc_test_proto_rawDescGZIP(), []int{14}
}

type CheckPredecessorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CheckPredecessorResponse) Reset() {
	*x = CheckPredecessorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_test_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckPredecessorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPredecessorResponse) ProtoMessage() {}

func (x *CheckPredecessorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_test_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPredecessorResponse.ProtoReflect.Descriptor instead.
func (*CheckPredecessorResponse) Descriptor() ([]byte, []int) {
	return file_rpc_test_proto_rawDescGZIP(), []int{15}
}

var File_rpc_test_proto protoreflect.FileDescriptor

var file_rpc_test_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x25, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x43, 0x68, 0x6f, 0x72, 0x64,
	0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4a, 0x0a, 0x14, 0x47,
	0x65, 0x74, 0x43, 0x68, 0x6f, 0x72, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x2c, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x69, 0x6e, 0x70, 0x75, 0x74, 0x22, 0x73, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x54, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x28, 0x0a, 0x0f,
	0x69, 0x6e, 0x70, 0x75, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x46, 0x72, 0x6f, 0x6d,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x2d, 0x0a, 0x11, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0xa6, 0x01, 0x0a, 0x12, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x68, 0x61, 0x73, 0x68, 0x65, 0x64, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x68, 0x61, 0x73, 0x68, 0x65, 0x64, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x2a, 0x0a, 0x10, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x10, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x2e, 0x0a, 0x12, 0x70, 0x72, 0x65, 0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f,
	0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12,
	0x70, 0x72, 0x65, 0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x22, 0x33, 0x0a, 0x0f, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x6a, 0x6f, 0x69, 0x6e, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6a, 0x6f, 0x69, 0x6e,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0xa4, 0x01, 0x0a, 0x10, 0x4a, 0x6f, 0x69, 0x6e,
	0x52, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x68, 0x61, 0x73, 0x68, 0x65, 0x64, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x68, 0x61, 0x73, 0x68, 0x65, 0x64, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x2a, 0x0a, 0x10, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x2e,
	0x0a, 0x12, 0x70, 0x72, 0x65, 0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x70, 0x72, 0x65, 0x64,
	0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x31,
	0x0a, 0x10, 0x53, 0x74, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x70, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x22, 0x40, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x7a, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x22, 0x36, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x64, 0x65, 0x63,
	0x65, 0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x69, 0x70, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x49, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x50, 0x72, 0x65, 0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x13, 0x70, 0x72, 0x65, 0x64, 0x65, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x12, 0x70, 0x72, 0x65, 0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x2e, 0x0a, 0x0d, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x70, 0x5f, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x70, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x41, 0x0a, 0x0e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x13, 0x70, 0x72, 0x65, 0x64,
	0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x70, 0x72, 0x65, 0x64, 0x65, 0x63, 0x65, 0x73, 0x73,
	0x6f, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x19, 0x0a, 0x17, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x50, 0x72, 0x65, 0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x1a, 0x0a, 0x18, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x72, 0x65,
	0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73,
	0x73, 0x6a, 0x68, 0x32, 0x33, 0x2f, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x2d, 0x67, 0x6f, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_test_proto_rawDescOnce sync.Once
	file_rpc_test_proto_rawDescData = file_rpc_test_proto_rawDesc
)

func file_rpc_test_proto_rawDescGZIP() []byte {
	file_rpc_test_proto_rawDescOnce.Do(func() {
		file_rpc_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_test_proto_rawDescData)
	})
	return file_rpc_test_proto_rawDescData
}

var file_rpc_test_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_rpc_test_proto_goTypes = []interface{}{
	(*GetChordNodeRequest)(nil),    // 0: pb.GetChordNodeRequest
	(*GetChordNodeResponse)(nil),   // 1: pb.GetChordNodeResponse
	(*GetRequestFromClient)(nil),   // 2: pb.GetRequestFromClient
	(*GetResponseToClient)(nil),    // 3: pb.GetResponseToClient
	(*CreateRingRequest)(nil),      // 4: pb.CreateRingRequest
	(*CreateRingResponse)(nil),     // 5: pb.CreateRingResponse
	(*JoinRingRequest)(nil),        // 6: pb.JoinRingRequest
	(*JoinRingResponse)(nil),       // 7: pb.JoinRingResponse
	(*StabilizeRequest)(nil),       // 8: pb.StabilizeRequest
	(*StabilizeResponse)(nil),      // 9: pb.StabilizeResponse
	(*GetPredecessorRequest)(nil),  // 10: pb.GetPredecessorRequest
	(*GetPredecessorResponse)(nil), // 11: pb.GetPredecessorResponse
	(*NotifyRequest)(nil),          // 12: pb.NotifyRequest
	(*NotifyResponse)(nil),         // 13: pb.NotifyResponse
}
var file_rpc_test_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_test_proto_init() }
func file_rpc_test_proto_init() {
	if File_rpc_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChordNodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChordNodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_test_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequestFromClient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_test_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponseToClient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_test_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_test_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_test_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_test_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_test_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StabilizeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_test_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StabilizeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_test_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPredecessorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_test_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPredecessorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_test_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_test_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_test_proto_goTypes,
		DependencyIndexes: file_rpc_test_proto_depIdxs,
		MessageInfos:      file_rpc_test_proto_msgTypes,
	}.Build()
	File_rpc_test_proto = out.File
	file_rpc_test_proto_rawDesc = nil
	file_rpc_test_proto_goTypes = nil
	file_rpc_test_proto_depIdxs = nil
}
