// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: successor_list.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSuccessorListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListSize      int32    `protobuf:"varint,1,opt,name=listSize,proto3" json:"listSize,omitempty"`
	SuccessorList []string `protobuf:"bytes,2,rep,name=successorList,proto3" json:"successorList,omitempty"`
}

func (x *GetSuccessorListRequest) Reset() {
	*x = GetSuccessorListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_successor_list_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSuccessorListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSuccessorListRequest) ProtoMessage() {}

func (x *GetSuccessorListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_successor_list_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSuccessorListRequest.ProtoReflect.Descriptor instead.
func (*GetSuccessorListRequest) Descriptor() ([]byte, []int) {
	return file_successor_list_proto_rawDescGZIP(), []int{0}
}

func (x *GetSuccessorListRequest) GetListSize() int32 {
	if x != nil {
		return x.ListSize
	}
	return 0
}

func (x *GetSuccessorListRequest) GetSuccessorList() []string {
	if x != nil {
		return x.SuccessorList
	}
	return nil
}

type GetSuccessorListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SuccessorList []string `protobuf:"bytes,1,rep,name=successorList,proto3" json:"successorList,omitempty"`
}

func (x *GetSuccessorListResponse) Reset() {
	*x = GetSuccessorListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_successor_list_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSuccessorListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSuccessorListResponse) ProtoMessage() {}

func (x *GetSuccessorListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_successor_list_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSuccessorListResponse.ProtoReflect.Descriptor instead.
func (*GetSuccessorListResponse) Descriptor() ([]byte, []int) {
	return file_successor_list_proto_rawDescGZIP(), []int{1}
}

func (x *GetSuccessorListResponse) GetSuccessorList() []string {
	if x != nil {
		return x.SuccessorList
	}
	return nil
}

var File_successor_list_proto protoreflect.FileDescriptor

var file_successor_list_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x5b, 0x0a, 0x17, 0x47, 0x65,
	0x74, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x69, 0x73, 0x74, 0x53, 0x69, 0x7a,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6c, 0x69, 0x73, 0x74, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x40, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x53, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x73, 0x6a, 0x68, 0x32, 0x33, 0x2f, 0x63,
	0x68, 0x6f, 0x72, 0x64, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_successor_list_proto_rawDescOnce sync.Once
	file_successor_list_proto_rawDescData = file_successor_list_proto_rawDesc
)

func file_successor_list_proto_rawDescGZIP() []byte {
	file_successor_list_proto_rawDescOnce.Do(func() {
		file_successor_list_proto_rawDescData = protoimpl.X.CompressGZIP(file_successor_list_proto_rawDescData)
	})
	return file_successor_list_proto_rawDescData
}

var file_successor_list_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_successor_list_proto_goTypes = []interface{}{
	(*GetSuccessorListRequest)(nil),  // 0: pb.GetSuccessorListRequest
	(*GetSuccessorListResponse)(nil), // 1: pb.GetSuccessorListResponse
}
var file_successor_list_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_successor_list_proto_init() }
func file_successor_list_proto_init() {
	if File_successor_list_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_successor_list_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSuccessorListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_successor_list_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSuccessorListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_successor_list_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_successor_list_proto_goTypes,
		DependencyIndexes: file_successor_list_proto_depIdxs,
		MessageInfos:      file_successor_list_proto_msgTypes,
	}.Build()
	File_successor_list_proto = out.File
	file_successor_list_proto_rawDesc = nil
	file_successor_list_proto_goTypes = nil
	file_successor_list_proto_depIdxs = nil
}
